config/routes.rb
GitLayers::Application.routes.draw do
  root to: 'welcome#index'

  # welcome controller routes
  get 'welcome/about', to: 'welcome#about'
  
  # session routes
  get 'sessions/create', to: 'sessions#create', as: 'create_session'
  get 'sessions/destroy', to: 'sessions#destroy', as: 'sessions_destroy'
  
  # users controller routes
  get 'users/login', to: 'users#login', as: 'login_user'
  get 'users/callback', to: 'users#callback'
  get 'user_profile', to: 'users#user_profile', as: 'user_profile'

  # repos controller routes
  get 'repos/user_repos', to: 'repos#user_repos', as: 'current_user_repos'
  get 'repos/repos', to: 'repos#repos', as: 'repos'
  get 'repos/commits', to: 'repos#repo_commits', as: 'repo_commits'
  

end

app/models/repo.rb
class Repo

	def self.fetch_repos(username, sort_type, access_token)
		user_repos = Rails.cache.fetch("user-name-#{username}", expires_in: 9000.seconds) do 
				JSON.parse(RestClient.get("https://api.github.com/users/#{username}/repos", {params: 
					{ access_token: access_token, 
						page: 1, 
						per_page: 100, 
						sort: sort_type}}))
			end
			user_repos.reject! do |repo|
				!repo['language']
			end
			return user_repos
	end

	def self.sort_repos_by_lang (repos)
		language_sorted = {}
		repos.each do |repo|
			language_sorted[repo['language']] ||= []
			language_sorted[repo['language']] << repo
		end
		return language_sorted.values.flatten
	end

	def self.split_by_forked(repos, user_login)
		repos.reject! do |repo|
			!repo['fork']
		end
	end

	def self.split_by_created(repos, user_login)
		repos.reject! do |repo|
			repo['fork']
		end
	
	end

	def self.generate_response(sort_type, split_type, token, username)
		
		puts username
		
		user_repos = Repo.fetch_repos(username, sort_type, token)

		user_repos.reject! do |repo|
			!repo['language']
		end

		if sort_type == 'lang'
			user_repos = Repo.sort_repos_by_lang(user_repos)
		end

		if split_type == 'forked'
			user_repos = Repo.split_by_forked(user_repos, username)
		elsif split_type == 'created'
			user_repos = Repo.split_by_created(user_repos, username)
		end

		return user_repos 

	end

	def self.fetch_repo_commits(commits_url, access_token)
		commits = Rails.cache.fetch("#{commits_url}", expires_in: 9000.seconds) do
			JSON.parse(RestClient.get(commits_url, {params:
				{ access_token: access_token,
					per_page: 100}}))
		end
		return commits
	end

end

app/models/user.rb
class User < ActiveRecord::Base

	def self.load_api_data(access_token, options={})

		if options[:username]
			url = "https://api.github.com/users/#{options[:username]}"
		else 
			url = "https://api.github.com/user"
		end

		github_user_data = Rails.cache.fetch("#{access_token}", :expires_in => 9000.seconds) do 
			JSON.parse(RestClient.get(url, {params: {:access_token => access_token}}))
		end

		return github_user_data

	end

	def self.extract_remote_params(github_user_data)
		params = {}
		params[:name] = github_user_data['name']
		params[:login] = github_user_data['login']
		params[:url] = github_user_data['url']
		params[:html_url] = github_user_data['html_url']
		params[:repos_url] = github_user_data['repos_url']
		params[:gists_url] = github_user_data['gists_url']
		params[:avatar_url] = github_user_data['avatar_url']
		params[:public_repos] = github_user_data['public_repos']
		params[:github_id] = github_user_data['id']
		params[:followers] = github_user_data['followers']
		params[:following] = github_user_data['following']
		params[:created_at] = github_user_data['created_at']
		params[:updated_at] = github_user_data['updated_at']
		params[:email] = github_user_data['email']
		return params
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery

  # defines current user by the session currently in progress
  helper_method :user_logged_in
  
  def user_logged_in
  		session[:access_token] != nil
  end

end

app/controllers/repos_controller.rb
class ReposController < ApplicationController
  # fetches commits for the passed commits url
  def repo_commits
    commits = Repo.fetch_repo_commits(params["commits_url"], session[:access_token])
    respond_to do |format|
      format.json { render json: commits }
    end
  end

  # fetches repositories of the user who is currently logged in
  def user_repos
    sort_type = params[:sort_type] || 'created'
    username = params['username']

    puts username

    user_repos = Repo.generate_response(sort_type, params[:split_type], session[:access_token], username)

    respond_to do |format|
      format.json { render json: user_repos } 
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # defines the session by the user currently logged in
  # redirects to index page
	def create
		session[:access_token] = params[:access_token]
		session[:logged_in_user] = params[:logged_in_user]
		session[:subject_user] = params[:subject_user]
		redirect_to root_url, notice: 'Logged In'
	end

  # logs out a user, removing the user from session
  # redirects to index page
	def destroy
		session[:subject_user] = nil
		session[:access_token] = nil
		session[:logged_in_user] = nil
		redirect_to root_url, notice: 'Logged Out'
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	# defines protocol for github api callback, logs user in
	def callback
		result = RestClient.post("https://github.com/login/oauth/access_token",
	    {client_id: ENV['CLIENT_ID'],
	     client_secret: ENV['CLIENT_SECRET'],
	     code: params[:code]
	    },{
	     :accept => :json
	    })
		redirect_to login_user_path(access_token: JSON.parse(result)['access_token'])
	end
	
	# extracts desired user information from github response and creates session
	def login
		user = User.extract_remote_params(User.load_api_data(params[:access_token]))
		redirect_to create_session_path(logged_in_user: user, access_token: params[:access_token])
	end

	# uses logged in user's information to render user profile
	def user_profile
		if !user_logged_in
			redirect_to '/'
		else
			user = User.load_api_data(session[:access_token], {username: params[:username]})
			@username_string = user['login']
			@user_repos = Repo.fetch_repos(@username_string, 'created', session[:access_token]).to_json.html_safe
			@username = @username_string.to_json.html_safe
			@name_string = user['name']
			@name = @name_string.to_json.html_safe
		end
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController 

  # routes user to home page unless they are logged in
	def index
		if user_logged_in
			redirect_to user_profile_path
		end
	end

	def about

	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_navbar.html.erb
<nav class='navbar' id='navbar-main-nav'>
  <a class='toggle' gumby-trigger='#navbar-main-nav #main-nav' href='#'>
    <i class='icon-menu'></i></a>
  <div style='margin:auto'>
    <ul id='main-nav'>
      <li><a href='/'>Layers</a></li>
      <li><a href='/welcome/about'>About</a></li>
      <% if user_logged_in %>
        <li><%=link_to 'Logout', sessions_destroy_path %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GitLayers</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
</head>
<body>
	<%= render 'layouts/navbar' %>

	<%= yield %>

</body>
</html>

app/views/users/_sort_buttons.html.erb
<div id='sort-button-wrapper'>
	<div class='medium default btn rounded selected-sort-button' >
		<a href='created' class='sort-button selected-sort'>Created</a>
	</div>
	<div class='medium info btn rounded' >
		<a href='updated' class='sort-button'>Recent</a>
	</div>
	<div class='medium info btn rounded' >
		<a href='full_name' class='sort-button'>Alphabetical</a>
	</div>
	<div class='medium info btn rounded' >
		<a href='lang' class='sort-button'>Language</a>
	</div>
</div>

app/views/users/user.html.erb
<div class='profile-section-header'><h2><%=@name_string || @username_string%>'s Repositories</h2></div>
<div id='repo-container-back' class='content-container'></div>
<script>
	Grid.initializeGrid(<%=@user_repos%>, <%=@username%>, <%=@name%>)
</script> 

app/views/users/user_profile.html.erb
<div class='profile-section-header'><h2><%=@name_string || @username_string%>'s Repositories</h2></div>
<div id='repo-container-back' class='content-container'></div>
<script>
	Grid.initializeGrid(<%=@user_repos%>, <%=@username%>, <%=@name%>)
</script> 

app/views/welcome/about.html.erb
<div id='about-title'>
	<h1 style='font-weight: 600'>GitHub Layers</h1>
</div>
<div class='content-container'>
<div id='about-message'>
	<p>
		<span> What </span> does your code's life look like? We all write it. We spend <span>days</span> writing it.
		Now lets see it. <span>Layers</span> uses your GitHub profile to form a visual representation of your projects, 
		displaying information about the programming <span>languages</span> you use most, the <span>scale</span> of the projects you work on,
		and the <span>people</span> you're working with.</p>
</div>

app/views/welcome/index.html.erb
<div class='content-container' id='home-page-content-container'>
	<div id='page-title'>
		<h1>
			<span>Code is Beautiful</span>
		</h1>
	</div>
	<h2 style='font-family:"Abel"'>Layer it</h2>
	<div class="xlarge info btn" id='login-button'>
		<a href='https://github.com/login/oauth/authorize?client_id=<%=ENV["CLIENT_ID"]%>'>GitHub Login</a>
	</div>
</div>

<script>
  Page.animateHomePage();
</script>